### ISSUE TITLE
Is this repo an unofficial implementation of "MegaPortraits: One-shot Megapixel Neural Head Avatars"

### ISSUE THREAD

**Issue by fmac2000** [Kevinfringe/MegaPortrait#1]

**Comment by Kevinfringe** [comment]
Yes, I'm still working on it, trying to figure out some implementation details mentioned in the paper.

**Comment by fmac2000** [comment]
Maybe these papers can clear the holes left in the implementation details?
[Free-HeadGAN](https://arxiv.org/pdf/2011.15126.pdf)
[Unsupervised High-Resolution Portrait Gaze Correction and Animation](https://arxiv.org/pdf/2207.00256.pdf)
[One-Shot Free-View Neural Talking-Head Synthesis for Video Conferencing](https://arxiv.org/pdf/2208.02210.pdf)

[A nice graph traversal tool for all the reference papers](https://www.connectedpapers.com/main/2ce170049bf997fad3fba146a5de2510ad54f797/MegaPortraits%3A-One%20shot-Megapixel-Neural-Head-Avatars/graph)

If you need any help with training let me know, we could train it on the three datasets and release it with this repo.
- Good luck! Please close this issue when its completed.

**Comment by fmac2000** [comment]
Hey Kevin - any updates on the upload?
